#!/bin/bash

# Copyright 2018 Jan Pazdziora
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

LOG=/data/startup-log
echo "" >> $LOG
echo "" >> $LOG

date >> $LOG
echo "Initializing data" >> $LOG
touch /data/.look-im-trying-to-run

/usr/local/bin/populate-volume-from-template /tmp /data
mkdir -p /run/log /data/var/log/journal

if [ ! -e /run/log/journal ]
then 
  ln -s /data/var/log/journal /run/log/journal
fi

echo "Data initialized... attempting to start radiusd" >> $LOG
touch /data/.look-i-ran
/usr/sbin/radiusd

echo "Radiusd running" >> $LOG
touch /data/.look-radiusd-ran


exec /usr/sbin/init
exit 10
